### ISSUE TITLE
ECC Key gen not working in v1.1

### ISSUE THREAD

**Issue by PoliceFighter761** [boatbomber/EncryptedNet#2]
After experimenting with this module I have noticed that in v1.1 the private key generation does not work. In v1.0 everything seems to work as expected.

I dont know if this is machine specific but no matter what I tried it always stayed at zeros. I'm switching back to v1.0 for now.

In v1.1 the private keys are all zeros!

Code is used to test:
```lua
local ecc1 = require(... ["EncryptedNet 1.1"].EllipticCurveCryptography)
local ecc2 = require(... ["EncryptedNet 1.0"].EllipticCurveCryptography)

-- Faulty code: (ecc 1.1)

-- Generate tokens
local serverPrivate, serverPublic = ecc1.keypair(ecc1.random.random())
local clientPrivate, clientPublic = ecc1.keypair(ecc1.random.random())

-- Check for overlap
print(serverPrivate:isEqual(clientPrivate))
print(serverPrivate:toHex())

print()
print()

-- Working code: (ecc 1.0)

-- Generate tokens
local serverPrivate, serverPublic = ecc2.keypair(ecc2.random.random())
local clientPrivate, clientPublic = ecc2.keypair(ecc2.random.random())

-- Check for overlap
print(serverPrivate:isEqual(clientPrivate))
print(serverPrivate:toHex())
```

Result:

![image](https://user-images.githubusercontent.com/53328446/163595578-91eb61f2-ffee-4b79-b0de-12f22db96130.png)

**Comment by boatbomber** [comment]
Great catch. Fixed in v1.0.2.

Problem was here:
https://github.com/boatbomber/EncryptedNet/commit/058634fce3b6c0d976b3a4439eb1848169e55d19#diff-ee2d4b5a822d47017c8a2d63b584d96424b6821db1aa7851fe21233961054241L372

@howmanysmall accidentally made it multiply by 256 + x instead of multiplying by 256 and then adding to that result. Easy fix!

**Comment by howmanysmall** [comment]
oops

**Comment by boatbomber** [comment]
My fault for not spotting in review.

**Comment by PoliceFighter761** [comment]
Adding a test for this could be a prevention for the future
But that's just my suggestion

**Comment by boatbomber** [comment]
If run-in-roblox ever works again 😔

**Comment by boatbomber** [comment]
(I'll set up a test suite in the meantime to run by hand, at least)

**Comment by boatbomber** [comment]
Added.
