### ISSUE TITLE
Bad actors can not send a handshake event to cause errors on the server

### ISSUE THREAD

**Issue by chloegit138** [boatbomber/EncryptedNet#3]
When calling Remote.SendToAllPlayers on an EncryptedNet remote, it doesn't check if players have indexes in PlayerData before calling SendToPlayer. This can cause errors if a player isnt initialized (or if a bad actor prevents the Handshake event from sending to cause an error). If one player fails, it wont send to any other players in the loop. An if statement should be added to check if they're initialized, and if not, retry the event in a second.

**Comment by chloegit138** [comment]
The flaw is in SendToPlayer itself, but it's a bigger issue in SendToAllPlayers since it effects the rest of the players. Bad actors can prevent data from getting to *anyone* by just joining the server first and not sending the handshake remote

**Comment by boatbomber** [comment]
This is fixed in v1.0.4, thanks for reporting it!
